server:
  port: 8082
spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8180/realms/nttdataproject
#          jwk-set-uri: http://localhost:8180/realms/nttdataproject/protocol/openid-connect/certs

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/Almacen
    username: postgres
    password: coopac@780**
